//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatGit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SatGitDBEntities : DbContext
    {
        public SatGitDBEntities()
            : base("name=SatGitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Favoriler> Favorilers { get; set; }
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Mesajlar> Mesajlars { get; set; }
        public virtual DbSet<Resimler> Resimlers { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    
        public virtual ObjectResult<KategoriliUrunAra_Result> KategoriliUrunAra(string urunAdi, string kategoriAdi)
        {
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var kategoriAdiParameter = kategoriAdi != null ?
                new ObjectParameter("KategoriAdi", kategoriAdi) :
                new ObjectParameter("KategoriAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KategoriliUrunAra_Result>("KategoriliUrunAra", urunAdiParameter, kategoriAdiParameter);
        }
    
        public virtual ObjectResult<UrunAra_Result> UrunAra(string urunAdi)
        {
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("urunAdi", urunAdi) :
                new ObjectParameter("urunAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunAra_Result>("UrunAra", urunAdiParameter);
        }
    }
}
